Refactor nextCastTime to DssExecLib
makerdao/dss-exec-lib pull request #74
Opened 2021-03-19 21:13 UTC by brianmcmichael

There's a lot of logic that is going in to the DssExec every week for the officehours functionality.

This creates two `pure` functions with optimized calldata that can be called directly from DssAction.

This should reduce the bytecode size of a weekly deployment with minimal impact on cast cost.

- `canCast`: returns true if the spell can be cast
- `nextCastTime`: used to determine the next castable time.

2021-03-23 15:03 UTC, hexonaut requested changes
Like the overall idea. A few changes suggested.

2021-03-23 15:03 UTC, hexonaut commented on src/test/DssAction.t.sol
> +        assertEq(action.nextCastTime_test(0, 1616256000, false), 1616256000);
Nit: Don't really need asserts here.

2021-03-23 15:03 UTC, hexonaut commented on src/test/DssAction.t.sol
> +        assertEq(action.nextCastTime_test(1616256000, 0, false), 1616256000);
Nit: Don't really need asserts here.

2021-03-23 15:11 UTC, gbalabasquer commented on src/DssExecLib.sol
> +            require(day < 5, "DssExecLib/Can only be cast on a weekday");
I agree.

2021-03-23 15:13 UTC, gbalabasquer commented
Did we check how close to the bytecode max size we got in `DssExecLib` with this change?

2021-03-23 15:24 UTC, gbalabasquer commented on src/DssExecLib.sol
> +            require(hour >= 14 && hour < 21, "DssExecLib/Outside office hours");
Same here.

2021-03-23 15:27 UTC, gbalabasquer commented on src/DssExecLib.sol
> +    function nextCastTime(uint40 _eta, uint40 _ts, bool _officeHours) public pure returns (uint256 castTime) {
Do we really need the `_ts` via param? Can't we just use `block.timestamp` here?

2021-03-23 15:28 UTC, hexonaut commented on src/DssExecLib.sol
> +    function nextCastTime(uint40 _eta, uint40 _ts, bool _officeHours) public pure returns (uint256 castTime) {
I could see this being useful in the case where you need to find the cast time from some arbitrary time instead of the current time.

2021-03-23 15:29 UTC, hexonaut commented on src/DssExecLib.sol
> +    function canCast(uint40 _ts, bool _officeHours) public pure returns (bool) {
Similarly here, especially if there are multiple spells that need to be executed one after the other for testing.

2021-03-23 16:11 UTC, gbalabasquer commented on src/DssExecLib.sol
> +    function canCast(uint40 _ts, bool _officeHours) public pure returns (bool) {
I think for this specific case we could just cast the first one, do `hevm.warp()`, cast the next one, etc.
I just feel that is more natural to use `block.timestamp` directly than having to pass it via param. Not strongly opposed to maintain it if you guys feel is better though.

2021-03-23 16:13 UTC, gbalabasquer commented on src/DssExecLib.sol
> +    function nextCastTime(uint40 _eta, uint40 _ts, bool _officeHours) public pure returns (uint256 castTime) {
I actually have some trouble considering this function should be in the exec-lib at all.
This is not used for the spell, this is for UIs or external contracts and it is needing a nested chain of external calls to expose it. This function could be addressed as well in an external contract that receives the spell as param which has nothing to do with this repo.

2021-03-23 16:13 UTC, gbalabasquer commented on src/DssExecLib.sol
> +    function nextCastTime(uint40 _eta, uint40 _ts, bool _officeHours) public pure returns (uint256 castTime) {
Removing it would also save bytecode space.

2021-03-23 21:09 UTC, brianmcmichael commented on src/DssExecLib.sol
> +    function canCast(uint40 _ts, bool _officeHours) public pure returns (bool) {
If we want this to be a `pure` function it needs to be here, otherwise it needs to be a `view`

2021-03-23 21:14 UTC, brianmcmichael commented on src/DssExecLib.sol
> +            require(day < 5, "DssExecLib/Can only be cast on a weekday");
Sounds good. We're probably not going to lose the detailed message if we don't revert in the function, but I think it's fine.

2021-03-23 21:16 UTC, brianmcmichael commented on src/DssExecLib.sol
> +    function nextCastTime(uint40 _eta, uint40 _ts, bool _officeHours) public pure returns (uint256 castTime) {
Yes, having this in a separate contract is something that would make sense. It's bureaucratically simpler to keep it here for now until we can find somewhere to put it.

An early design had this function on the factory contract and it just called back to it.

2021-03-24 12:09 UTC, gbalabasquer commented on src/DssExecLib.sol
> +    function canCast(uint40 _ts, bool _officeHours) public pure returns (bool) {
Yeah, not sure which other types of usage this function will receive, I just feel for the current usage could be simpler. But up to you guys whatever prefer.

2021-03-24 12:10 UTC, gbalabasquer commented on src/DssExecLib.sol
> +    function nextCastTime(uint40 _eta, uint40 _ts, bool _officeHours) public pure returns (uint256 castTime) {
Might be just a support contract that handles it and nothing else.

2021-03-24 17:53 UTC, hexonaut approved these changes
Tests passing. LGTM. I don't have strong feelings about including the `block.timestamp` or not.

2021-03-24 18:29 UTC, brianmcmichael commented on src/DssAction.sol
> +        castTime = DssExecLib.nextCastTime(uint40(eta), uint40(block.timestamp), officeHours());
Actually this needs the `require` check again because the param is `uint256` and this can silently overflow.

2021-03-24 18:30 UTC, brianmcmichael commented on src/DssExecLib.sol
> +        require(_ts  != 0 && _ts  < uint40(-1));  // "DssExecLib/invalid ts"
These `uint40` checks are unnecessary because the params are `uint40`

2021-03-25 12:10 UTC, hexonaut commented
I don't think we should be pulling these out into a separate library. This is going to require us to add a new library reference on every spell which takes up time and additional bytecode making reference to an additional library. I think as a practical matter I would prefer to keep everything in dss-exec-lib until we start bumping up against the bytecode limit.

2021-03-25 15:53 UTC, gbalabasquer commented
I agree with Sam. I would remove `nextCastTime` from the execlib to move it to somewhere else which the spell itself has nothing to do. Like a support contract. I know that would change things for UI people, but shouldn't be a big deal.
If that doesn't happen, then I prefer to keep one library until we reach the limit.

2021-03-25 17:08 UTC, hexonaut commented
Yeah that's a good point. It isn't used by the spell directly. It should probably be just some utility contract that can be pulled in when needed.

2021-04-05 21:37 UTC, brianmcmichael commented
I moved everything back to the library for now. I've always thought that the time stuff would be a good candidate for an external reference contract, but that's going to be a more involved deployment process. We've still got space here for now.

2021-04-11 14:21 UTC, hexonaut approved these changes
LGTM. 👍

2021-04-12 15:14 UTC, godsflaw approved these changes
LGTM

2021-04-12 15:15 UTC, merged