Liquidations 2.0
makerdao/dss-exec-lib pull request #78
Opened 2021-04-27 22:03 UTC by brianmcmichael

Pretty substantial overhaul.

Updates the DssExecLib for Liquidations 2.0.
Adds new functionality for Clippers, Dogs, and Calcs.

This is a destructive change that removes our ability to deploy the old "Flipper" type collaterals. If we do need to deploy a new collateral as a Flipper type, we can use [Release 0.0.6](https://github.com/makerdao/dss-exec-lib/releases/tag/v0.0.6) for the time being. If we get in the habit of continuing to do the old type we can revisit this, but I'm under the assumption that all new collaterals will be Liq2.0.

2021-04-29 14:46 UTC, hexonaut requested changes
Mostly looks good. I've added a few recommendations. There is a missing critical piece for the collateral addition though. Haven't looked at the tests yet, but they are passing at least.

2021-04-29 14:46 UTC, hexonaut commented on src/DssExecLib.sol
> +        (bool ok,) = clip(_ilk).call(abi.encodeWithSignature("upchost()")); ok;
What is the purpose of this `ok;` at the end?

2021-04-29 14:46 UTC, hexonaut commented on src/DssExecLib.sol
> +        (bool ok,) = clip(_ilk).call(abi.encodeWithSignature("upchost()")); ok;
Again with the `ok;` at the end?

2021-04-29 14:46 UTC, hexonaut commented on src/DssExecLib.sol
> +        Fileable(clip(_ilk)).file("buf", _pct_bps * RAY / 10000);
Change to `rdiv(_pct_bps, BPS_ONE_HUNDRED_PCT)`.

2021-04-29 14:46 UTC, hexonaut commented on src/DssExecLib.sol
> +        Fileable(clip(_ilk)).file("cusp", _pct_bps * RAY / 10000);
Change to `rdiv(_pct_bps, BPS_ONE_HUNDRED_PCT)`.

2021-04-29 14:46 UTC, hexonaut commented on src/DssExecLib.sol
> +        Fileable(clip(_ilk)).file("chip", _pct_bps * WAD / 10000);
Change to `wdiv(_pct_bps, BPS_ONE_HUNDRED_PCT)`.

2021-04-29 14:46 UTC, hexonaut commented on src/DssExecLib.sol
> +        MomLike(clipperMom()).setPriceTolerance(_clip, _pct_bps * RAY / 10000);
Change to `rdiv(_pct_bps, BPS_ONE_HUNDRED_PCT)`.

2021-04-29 14:46 UTC, hexonaut commented on src/DssExecLib.sol
> +        Fileable(_calc).file("cut", _pct_bps * RAY / 10000);
Change to `rdiv(_pct_bps, BPS_ONE_HUNDRED_PCT)`.

2021-04-29 14:46 UTC, hexonaut commented on src/DssExecLib.sol
> +    }
I think these should be `setXXXX` instead of `initXXXX` to match the other functions. If you look at `setIlkAutoLineParameters` which is sort of an "initialization" as well. Alternatively I would rename things like `setIlkAutoLineParameters` to `initIlkAutoLineParameters`. It should be consistent whichever way you want to go.

2021-04-29 14:46 UTC, hexonaut commented on src/DssExecLib.sol
> +        Fileable(_calc).file("cut", _pct_bps * RAY / 10000);
Change to `rdiv(_pct_bps, BPS_ONE_HUNDRED_PCT)`.

2021-04-29 14:46 UTC, hexonaut commented on src/DssExecLib.sol
> +        require(AuctionLike(_clip).vat() == _vat);  // "clip-vat-not-match"
Add `require(AuctionLike(_clip).spotter() == _spotter);  // "clip-spotter-not-match"`

2021-04-29 14:46 UTC, hexonaut commented on src/DssExecLib.sol
> +        // Set the ilk Clipper in the Cat
`Cat` should be `Dog`

2021-04-29 14:46 UTC, hexonaut commented on src/DssExecLib.sol
> +		// Allow the ilk Clipper to reduce the Dog hole on deal()
Tabs should be spaces.

2021-04-29 14:46 UTC, hexonaut commented on src/DssExecLib.sol
> +            authorize(co.clip, clipperMom());
Need to add clipper mom access to pip as well `addReaderToOSMWhitelist(co.pip, clipperMom());`

2021-04-29 14:46 UTC, hexonaut commented on src/DssExecLib.sol
> +
Is there any reason in particular we are not passing these as arguments in the `CollateralOpts` struct?

2021-05-03 14:16 UTC, brianmcmichael commented on src/DssExecLib.sol
> +        (bool ok,) = clip(_ilk).call(abi.encodeWithSignature("upchost()")); ok;
Clears up a compiler warning. And the compilation fails if we don't use the return from the address.call()

2021-05-03 14:18 UTC, brianmcmichael commented on src/DssExecLib.sol
> +
Reduction in scope. We can always set these afterward if we intend to use them.

2021-05-04 10:42 UTC, hexonaut commented on src/DssExecLib.sol
> +        (bool ok,) = clip(_ilk).call(abi.encodeWithSignature("upchost()")); ok;
Ah ok.

2021-05-04 10:45 UTC, hexonaut commented on src/DssExecLib.sol
> +
Primoz seems to want to usually set the chip. I think the more we can make this an "all-in-one" sort of function the easier it will be to not forget something accidentally.

Even beyond this I think we should start including the autoline config params in here as well as it has become common. IMO the add collateral should be taking whatever common path we happen to be using at the time. What do you think?

2021-05-04 13:35 UTC, gbalabasquer commented on src/DssExecLib.sol
>      }
Maybe just have one `xlip` function?

2021-05-04 13:38 UTC, gbalabasquer commented on src/DssExecLib.sol
> +        (bool ok,) = clip(_ilk).call(abi.encodeWithSignature("upchost()")); ok;
Any reason why not calling directly `upchost` instead of using `call`? I don't see a way it would fail excepting overflow, which should be a situation to revert anyway.

2021-05-04 13:39 UTC, gbalabasquer commented on src/DssExecLib.sol
> +        (bool ok,) = clip(_ilk).call(abi.encodeWithSignature("upchost()")); ok;
Same here.

2021-05-04 13:53 UTC, gbalabasquer commented on src/DssExecLib.sol
> +            deauthorize(co.clip, dog());
I wouldn't do this. For this module we have the levels. So I'd keep the authorization and do `co.clip.file("stopped", 3)`.

2021-05-04 13:56 UTC, gbalabasquer commented on src/DssExecLib.sol
> +
IMO at least `chip` should be enabled. I'd prefer both.
Regarding auto-line. Do we know if the new collaterals will come with it by default?

2021-05-04 14:05 UTC, e18r commented on src/DssExecLib.sol
>      }
Soon we will only have `clip`s, so having a distinct `clip` function makes it more readable, IMO

2021-05-04 15:00 UTC, gbalabasquer commented on src/DssExecLib.sol
>      }
Well we are forwarding the `ilkRegistry` function which has a `xlip` and will keep having so.
I'd prefer to be more explicit on not make the user think is bringing a `flip` when might be a `clip` or viceversa.

2021-05-04 15:01 UTC, hexonaut commented on src/DssExecLib.sol
> +
I don't see why not. Almost all current collaterals have it.

2021-05-04 16:59 UTC, brianmcmichael commented on src/DssExecLib.sol
> +        (bool ok,) = clip(_ilk).call(abi.encodeWithSignature("upchost()")); ok;
This function still works with Flips, so it would fail.

2021-05-04 18:31 UTC, gbalabasquer commented on src/DssExecLib.sol
> +        (bool ok,) = clip(_ilk).call(abi.encodeWithSignature("upchost()")); ok;
Ah right, didn't think about that. Other option would be checking the ilkRegistry class, but yeah is cheaper this way.

2021-05-04 18:34 UTC, e18r commented on src/DssExecLib.sol
>      function ttl() external returns (uint256);
Currently only being used for Clippers. Better change to ClipLike and remove unused functions:

    interface ClipLike {
        function vat() external returns (address);
        function dog() external returns (address);
        function ilk() external returns (bytes32);
    }

2021-05-04 18:38 UTC, e18r commented on src/DssExecLib.sol
> +
maybe worth adding a `function calc(bytes32 _ilk)`?

2021-05-04 19:06 UTC, e18r commented on src/DssExecLib.sol
>      }
update comments in lines 360 and 369

2021-05-04 19:50 UTC, e18r commented on src/DssExecLib.sol
> +
remove whitespace

2021-05-04 19:51 UTC, e18r commented on src/DssExecLib.sol
>          require(_amount < WAD);  // "LibDssExec/incorrect-vow-dump-precision"
update comment

2021-05-04 19:53 UTC, brianmcmichael commented on src/DssExecLib.sol
>      }
what do you mean here?

2021-05-04 19:54 UTC, e18r commented on src/DssExecLib.sol
> +        Fileable(dog()).file("Hole", _amount * RAD);
I know you said in the description of this PR that this is backwards-incompatible, but I see no harm in replicating this with the dog instead of replacing it. After all, we still have the cat variable.

2021-05-04 20:03 UTC, brianmcmichael commented on src/DssExecLib.sol
>      }
Yeah I kind of saw this as transitional code. I don't particularily like the `xlip` nomenclature. Another option would be to put a require in here that asserts that `class` == 1 for clips and 2 for flips. Not sure.

2021-05-04 20:05 UTC, brianmcmichael commented on src/DssExecLib.sol
> +
I've added tip and chip to collateralopts. It's going to be a bigger change to convert onboarding to use dss-auto-line out of the box. I'd rather not default to it here as we can activate it with one line.

2021-05-04 20:27 UTC, e18r commented on src/DssExecLib.sol
> +        Fileable(clip(_ilk)).file("tail", _duration);
maybe make sure this doesn't exceed, say, one month? I know we're not checking duration values elsewhere, but we have to start somewhere

2021-05-04 20:33 UTC, e18r commented on src/DssExecLib.sol
> +        require(_pct_bps < BPS_ONE_HUNDRED_PCT); // "LibDssExec/incorrect-clip-cusp-precision"
```suggestion
        require(_pct_bps < BPS_ONE_HUNDRED_PCT); // "LibDssExec/incorrect-clip-cusp-precision"
        require(_pct_bps > 0); // "LibDssExec/incorrect-clip-cusp-value"
```

2021-05-04 20:37 UTC, e18r commented on src/DssExecLib.sol
>      }
some outdated comments about setting the cat contract in the vat (which has never been possible IIRC)

2021-05-04 20:38 UTC, e18r commented on src/DssExecLib.sol
>      }
probably the line numbers have changed, but it's in the system configuration section

2021-05-04 20:41 UTC, e18r commented on src/DssExecLib.sol
> +        require(_pct_bps < BPS_ONE_HUNDRED_PCT);  // "LibDssExec/incorrect-ilk-chop-precision"
update comment to incorrect-clippermom-price-tolerance

although I'm not sure it's worth updating these comments lol

2021-05-04 20:45 UTC, e18r commented on src/DssExecLib.sol
> +    }
agreed, `init` conveys the idea of initialization, but in this case we're filing parameters.

2021-05-04 20:46 UTC, brianmcmichael commented on src/DssExecLib.sol
> +        require(_pct_bps < BPS_ONE_HUNDRED_PCT);  // "LibDssExec/incorrect-ilk-chop-precision"
no, it's fine, let's do it right

2021-05-04 20:47 UTC, e18r commented on src/DssExecLib.sol
> +        Fileable(_calc).file("cut", _pct_bps * RAY / 10000);
```suggestion
```

It's more practical to have one function to set `cut` (the below one) and one to set `step`. Update comments accordingly.

2021-05-04 20:49 UTC, e18r commented on src/DssExecLib.sol
> +        require(_pct_bps < 10000); // DssExecLib/cut-too-high
```suggestion
        require(_pct_bps < BPS_ONE_HUNDRED_PCT); // DssExecLib/cut-too-high
```

2021-05-04 21:21 UTC, e18r commented on src/DssExecLib.sol
> +        // Authorize the ESM to ececut in the clipper
```suggestion
        // Authorize the ESM to execute in the clipper
```

2021-05-04 21:24 UTC, e18r commented on src/DssExecLib.sol
> +            // Allow clipperMom to access to the ilk Clipper
```suggestion
            // Grant clipperMom access to the ilk Clipper
```

2021-05-04 21:30 UTC, e18r commented on src/DssExecLib.sol
> +            Fileable(co.clip).file("stopped", 3);
we should have a function for this.

2021-05-04 21:32 UTC, e18r commented on src/DssExecLib.sol
>          setIlkMaxLiquidationAmount(co.ilk, co.maxLiquidationAmount);
shouldn't the general Hole be updated as well?

2021-05-04 21:35 UTC, e18r approved these changes
LGTM, left some comments

2021-05-05 10:46 UTC, hexonaut commented on src/DssExecLib.sol
> +
Yeah for sure. Changing the auto-line should be in a different PR to be discussed separately from this.

2021-05-05 12:53 UTC, gbalabasquer commented on src/DssExecLib.sol
> +            Fileable(co.clip).file("stopped", 3);
Yes we should probably have functions for all the `file` types. But that probably should go in another PR.

2021-05-05 13:02 UTC, gbalabasquer commented on src/DssExecLib.sol
>          setIlkMaxLiquidationAmount(co.ilk, co.maxLiquidationAmount);
The general `Hole` is an independent value of the `ilk`s. E.g. we have it set to 100M right now and it is not changing each time we add new clippers.
With the `Line` we came to this sort of rule that is the sum of all the `line`s but shouldn't be a constraint at all.

2021-05-05 21:37 UTC, brianmcmichael commented on src/DssExecLib.sol
> +        Fileable(clip(_ilk)).file("tail", _duration);
I'm not sure if this is a safe assumption. We might have stablecoin auctions with little to no drop an no expiration. Maybe let's go with 3 months for now and we can revisit if it becomes a problem.

2021-05-05 21:39 UTC, brianmcmichael commented on src/DssExecLib.sol
> +            Fileable(co.clip).file("stopped", 3);
We have `setContract` for address file types, but yeah, maybe more for values. I will go ahead and make one for this and we can expand in another PR later.

2021-05-05 21:47 UTC, brianmcmichael commented on src/DssExecLib.sol
> +            Fileable(co.clip).file("stopped", 3);
So check this out. I made a function `setValue()` to handle the files and we can update everything to use it. I've put a couple of examples in at [`86799fe` (#78)](https://github.com/makerdao/dss-exec-lib/pull/78/commits/86799fea7fa1f8a9a6ee5c8ee4436eb97cd0fd66#diff-72201ff20380f5c7fc89281be3ad2dd6bd5a992f246d41d6d9d97f71e078d40dR383)

If we like it I can update the rest of the contract to use it.

2021-05-05 22:33 UTC, brianmcmichael commented on src/DssExecLib.sol
> +        Fileable(_calc).file("cut", _pct_bps * RAY / 10000);
I don't really think it's more practical to have these separate in this case. Each of these calcs have unique and inconsistent fileable parameters that need to be called to properly initialize them, because they aren't handled in the constructors. Forcing them to do them both at the same time ensure they'll be properly initialized, since they aren't standard across the Abacus variations.

2021-05-05 22:35 UTC, brianmcmichael commented on src/DssExecLib.sol
> +    }
Here we really are initializing these though. After deploying a new calc, these component functions need to be called for it to work correctly. Ideally this would have been handled in the respective constructors but for now they effectively need to be initialized to work.

2021-05-07 16:50 UTC, hexonaut commented on src/DssExecLib.sol
> +            addReaderToOSMWhitelist(OracleLike(_oracle).src(), _oracle);
This should be `addReaderToMedianWhitelist(OracleLike(_oracle).src(), _oracle);` as `OracleLike(_oracle).src()` is a median. The function is the same though, so it won't trip the tests.

2021-05-07 16:50 UTC, hexonaut commented on src/DssExecLib.sol
> +    }
That's fine. I would consider changing stuff like `setIlkAutoLineParameters` to `initIlkAutoLineParameters` as well then to convey the idea of initialization.

2021-05-07 17:03 UTC, hexonaut reviewed
Mostly looks good. A couple minor comments.

2021-05-07 17:03 UTC, hexonaut commented on src/DssExecLib.sol
> +        setLiquidationBreakerPriceTolerance(co.clip, 5000);
I still think this should be explicitly specified in the collateral args just so it doesn't get accidentally overlooked.

2021-05-10 14:26 UTC, brianmcmichael commented on src/DssExecLib.sol
> +        authorize(co.clip, clipperMom_);
We're handling liquidations in the clip now using the circuit breaker.

2021-05-10 17:42 UTC, brianmcmichael commented on src/DssExecLib.sol
> +        authorize(co.clip, clipperMom_);
Yeah, you're right. I think this change came out of a conversation with @gbalabasquer and you make a good point that a governance attack could liquidate collateral out-of-pause. I will move this back and update the tests to ensure wards are `0` here. Pinging Gonza in case we're missing something.

2021-05-11 11:49 UTC, hexonaut approved these changes
LGTM 👍 I still think the `setLiquidationBreakerPriceTolerance()` should be provided as a parameter, but if you want to leave it out that's fine.

2021-05-12 15:40 UTC, e18r commented on src/DssExecLib.sol
> +        @param _base   The address of the contract where the new contract address will be filed
@param _base   The address of the contract where the new ~~contract address~~ value will be filed

2021-05-12 15:42 UTC, e18r commented on src/DssExecLib.sol
> +            Fileable(co.clip).file("stopped", 3);
Nice, I like it. We probably need more functions to handle values that aren't `uint256`.

2021-05-12 15:48 UTC, e18r commented on src/DssExecLib.sol
>      }
It's true what @gbalabasquer says, but I agree it's better to have two separate functions and put `require`s on them.

2021-05-12 15:50 UTC, e18r commented on src/DssExecLib.sol
> +        Fileable(_calc).file("cut", _pct_bps * RAY / 10000);
Fair enough. I thought these were also going to be used for filing params in the abaci. But if that's not the main use case, then it's OK.

2021-05-12 15:52 UTC, e18r commented on src/DssExecLib.sol
> +        @param _base   The address of the contract where the new contract address will be filed
~~contract address~~ value

2021-05-12 15:53 UTC, e18r commented on src/DssExecLib.sol
> +        @dev Set a value in a contract, via a governance authorized File pattern.
~~a value~~ an ilk-specific value

2021-05-12 15:56 UTC, e18r commented on src/DssExecLib.sol
> +        @dev Allows an oracle to read prices from it's source feeds
~~it's~~ its

2021-05-12 16:03 UTC, e18r commented on src/DssExecLib.sol
> +            median0 = abi.decode(data, (address));
```suggestion
        (bool ok, bytes memory data) = _oracle.call(abi.encodeWithSignature("orb0()"));
        if (ok) {
            // Token is an LP oracle
            address median0 = abi.decode(data, (address));
```

2021-05-12 16:19 UTC, e18r commented on src/test/DssAction.t.sol
> +        Median  med0   = new Median();
In real life this would be the medianizers relying the Pause Proxy, right?

2021-05-12 16:19 UTC, e18r commented on src/test/DssAction.t.sol
> +        med0.rely(address(action));
In real life this would be the medianizers relying the Pause Proxy, right?

2021-05-12 16:22 UTC, e18r commented on test.sh
> +export DAPP_BUILD_OPTIMIZE=1
I just checked build.sh and we are also using the optimizer. Is this really what we want? This is pretty critical code.

2021-05-12 16:27 UTC, e18r reviewed
LGTM except for the optimizer. I think it should be disabled.

2021-05-24 14:50 UTC, gbalabasquer commented
> LGTM except for the optimizer. I think it should be disabled.

IMO for this one can be enabled. It is not a core and permanent contract. The risks a bug on the optimizer

2021-05-24 16:18 UTC, e18r commented
After further discussions with the team, the optimizer is a separate issue. I'm OK with merging this PR without taking into account the optimizer.

2021-06-07 21:06 UTC, brianmcmichael commented on src/test/DssAction.t.sol
> +        med0.rely(address(action));
Yes. The DssAction test file is only testing that the actions are updating the contract values correctly using a test deployment. RPC tests against the pauseProxy are happening in DssExec

2021-06-07 21:08 UTC, brianmcmichael commented on test.sh
> +export DAPP_BUILD_OPTIMIZE=1
AFAIK @gbalabasquer has been deploying exec's optimized for 1 run. We should confirm whether we're still doing that.

2021-06-07 21:35 UTC, brianmcmichael commented
I think I've addressed all comments, ready for another look @gbalabasquer @e18r @hexonaut

2021-06-08 18:06 UTC, merged