Comment CollateralOpts.sol, update README.md
makerdao/dss-exec-lib pull request #88
Opened 2021-11-30 22:23 UTC by canokaue

- create variable comments in CollateralOpts.sol; 
- add breakerTolerance, kprFlatReward & kprPctReward variables to README.md examples;
- add setIlkAutoLineParameter method call to README.md example;
- change initStairstepExponentialDecrease to setStairstepExponentialDecrease;
- match Maker governance proposal parameters with CollateralOpts.

2021-12-13 22:01 UTC, brianmcmichael commented on src/CollateralOpts.sol
> +    bytes32 ilk;                      // bytes32 result of the hyphenated, all caps token vault name (e.g. "WBTC-C")
There's a lot of text here. I wonder if it wouldn't be better to create a glossary and link to it.

2021-12-13 22:02 UTC, brianmcmichael commented on README.md
> +- `calc`:                 Address of Abacus pricing contract, "Auction Price Function (calc)" gov proposal parameter
I don't know if the contracts should have knowledge of governance labels, and I'm not sure they are standardized anyway.

2021-12-14 15:27 UTC, canokaue commented on README.md
> +- `calc`:                 Address of Abacus pricing contract, "Auction Price Function (calc)" gov proposal parameter
> 

Indeed, they're not (and already changed since the PR). CES has this info in a Notion doc, I'll edit back the PR to just the README update and coordinate with the rest of the folks to post it to an existing docs site. Thanks Brian!

2022-01-05 16:53 UTC, brianmcmichael commented on src/CollateralOpts.sol
> +    bytes32 ilk;
Please trim the excess spaces in this file. You can configure your editor to do this automatically.

2022-01-05 16:53 UTC, brianmcmichael commented on src/CollateralOpts.sol
> +    bool isLiquidatable;
Please keep the original alignment. I think you can probably just git stash this whole file.

2022-01-05 16:55 UTC, brianmcmichael commented on src/CollateralOpts.sol
> +    bool isLiquidatable;
The class comments are fine though, don't stash.

2022-01-05 16:58 UTC, brianmcmichael commented on README.md
> +- `minVaultAmount`:       Minimum DAI vault amount a particular user can generate at a time
Not sure about the "at a time" part. The limitation is only on the vault. Once it's above the dust you can generate or repay in smaller amounts.

2022-01-05 16:59 UTC, brianmcmichael commented on README.md
> +- `ilkDebtCeiling`:       Debt ceiling (maximum amount of DAI able to be minted from a given vault collectively) for new collateral
The debt ceiling does not apply to vaults specifically, it's the total Dai that can be generated out of that particular ilk by all vaults.

2022-01-17 12:11 UTC, canokaue commented
Hey @brianmcmichael thank you so much for the feedback! I've added your suggestions to the latest commit [6ad733d4050bb9234b84ac81c400c052c21fa107](https://github.com/makerdao/dss-exec-lib/pull/88/commits/6ad733d4050bb9234b84ac81c400c052c21fa107), please let me know if it's all good now.
Have a great week.

2022-01-25 21:44 UTC, iamchrissmith requested changes
@canokaue this is looking good, I made a couple of wording suggestions

2022-01-25 21:44 UTC, iamchrissmith commented on README.md
> +- `gem`:                  Address of the particular underlying token (e.g. WBTC), found in the latest MCD deployment
```suggestion
- `gem`:                  Address of the particular underlying token (e.g. WBTC)
```

The last piece made it sound like WBTC was deployed with DSS in my opinion

2022-01-25 21:44 UTC, iamchrissmith commented on README.md
> +- `minVaultAmount`:       Minimum DAI vault amount a particular user can generate
```suggestion
- `minVaultAmount`:       Minimum debt denominated in DAI a single vault can have (dust)
```

2022-01-25 21:44 UTC, iamchrissmith commented on README.md
> +- `breakerTolerance`:     Percentage of how large of a price drop is tolerated before liquidations are paused [ex. 0.5x == 50% == 5000 bps]
@brianmcmichael is this in one oracle update or over some other measure of time?  Also how do auctions get turned back on? Is that a governance action?

2022-01-25 21:44 UTC, iamchrissmith commented on README.md
> +- `liquidationRatio`:     Basis point percent liquidation ratio for new collateral, sets the maximum amount of DAI debt that a vault user can draw from their vault given the value of their collateral
```suggestion
- `liquidationRatio`:     Basis point percent liquidation ratio for new collateral, sets the maximum amount of DAI debt that a vault can have given the value of their collateral locked in that vault [ex. 150% == 15000] without facing liquidation
```

2022-01-25 21:44 UTC, iamchrissmith commented on src/CollateralOpts.sol
> +// Copyright (C) 2021 Maker Ecosystem Growth Holdings, Inc.
I think this should be 
```suggestion
// Copyright (C) 2021-2022 Dai Foundation
```

2022-01-25 21:44 UTC, iamchrissmith commented on src/CollateralOpts.sol
> +    bool whitelistOSM;
I would keep the indentation in as it aligns the variable names with the others

2022-01-26 03:47 UTC, brianmcmichael commented on README.md
> +- `breakerTolerance`:     Percentage of how large of a price drop is tolerated before liquidations are paused [ex. 0.5x == 50% == 5000 bps]
Check out the ClipperMom for details. There's some documentation there on [setPriceTolerance](https://github.com/makerdao/clipper-mom/blob/master/src/ClipperMom.sol#L115-L122) and also [tripBreaker](https://github.com/makerdao/clipper-mom/blob/master/src/ClipperMom.sol#L134-L156)

2022-01-26 03:47 UTC, brianmcmichael commented on README.md
> +- `breakerTolerance`:     Percentage of how large of a price drop is tolerated before liquidations are paused [ex. 0.5x == 50% == 5000 bps]
maybe the comment here can mention it's for the clipperMom's price breaker.

2022-02-07 21:24 UTC, brianmcmichael commented on README.md
> +- `gem`:                  Address of the particular underlying token (e.g. WBTC)
```suggestion
- `gem`:                  Address of underlying token (e.g. WBTC)
```

2022-02-07 21:30 UTC, brianmcmichael commented on README.md
> +- `ilk`:                  Bytes32 result of the hyphenated, all caps collateral type name (e.g. "WBTC-C")
I'm not sure this extended description is required. It's possible governance may choose other labeling methodologies.

Consider the following. 

```suggestion
- `ilk`:                  Collateral type (e.g. "WBTC-C")
```

2022-02-07 21:31 UTC, brianmcmichael commented on README.md
> +- `ilkDebtCeiling`:       Debt ceiling (maximum amount of DAI able to be minted from a given ilk collectively) for new collateral
```suggestion
- `ilkDebtCeiling`:       Debt ceiling (maximum amount of DAI able to be minted from a given ilk) for new collateral
```

2022-02-17 18:14 UTC, brianmcmichael approved these changes

2022-02-22 21:08 UTC, iamchrissmith approved these changes
lgtm

2022-03-09 14:34 UTC, canokaue commented
@brianmcmichael @iamchrissmith thanks for reviewing and approving the PR. I believe we're good to merge, but I can't do it on my end.

2025-05-06 22:18 UTC, amusingaxl commented
Closing as this no longer relevant.

2025-05-06 22:18 UTC, closed without merging