set RWA DC
makerdao/dss-exec-lib pull request #93
Opened 2022-03-01 22:07 UTC by julienmartinlevrai

2022-03-16 18:17 UTC, godsflaw approved these changes
LGTM

2022-03-22 19:12 UTC, brianmcmichael commented on src/DssAction.sol
> +// Copyright (C) 2018-2022 Dai Foundation
I'm not sure this is appropriate. The Dai Foundation and this code did not exist in 2018 and this code in particular was developed under the Maker Foundation.
I think it's probably more appropriate to keep the original line and add a new one reflecting the Dai Foundation's copyright claim.

2022-03-22 19:16 UTC, brianmcmichael commented on src/DssAction.sol
> +    function nextCastTime(uint256 eta) external view returns (uint256 castTime) {
Similar comment to line #42.

2022-03-22 19:24 UTC, julienmartinlevrai commented on src/DssAction.sol
> +    function officeHours() public virtual pure returns (bool) {
Some sort of conditional office hours ?

2022-03-22 19:28 UTC, julienmartinlevrai commented on src/DssAction.sol
> +    function nextCastTime(uint256 eta) external view returns (uint256 castTime) {
What do you mean ? This function is not virtual.

2022-03-22 19:38 UTC, julienmartinlevrai commented on src/DssAction.sol
> +// Copyright (C) 2018-2022 Dai Foundation
pushed

2022-03-22 20:05 UTC, julienmartinlevrai commented on src/DssAction.sol
> +    function officeHours() public virtual pure returns (bool) {
I tested a non-pure override, and it causes a compile-time error. So I will change this to `view`, since I think we can agree that this function does not need to modify state.

2022-03-22 20:08 UTC, julienmartinlevrai commented on src/DssAction.sol
> +    function officeHours() public virtual pure returns (bool) {
pushed

2022-03-24 15:05 UTC, talbaneth commented on src/DssExecLib.sol
> +        @param _price    The new oracle price in natural units
Just a suggestion - since `_price` is a tricky parameter to configure, maybe add a comment hinting on how to calculate it. Something like:
"_price should enable DAI to be drawn over the loan period while taking into account the configured ink amount, interest rate and liquidation ratio".
See example in https://github.com/makerdao/spells-mainnet/blob/master/archive/2021-07-17-DssSpell/DssSpell.sol#L53

2022-03-24 21:23 UTC, julienmartinlevrai commented
@naszam fixed, thank you

2022-03-24 21:25 UTC, julienmartinlevrai commented on src/DssExecLib.sol
> +        @param _price    The new oracle price in natural units
good suggestion, done

2022-03-28 12:21 UTC, naszam commented
Following https://github.com/makerdao/dss-direct-deposit/pull/35, I think we can `dapp upgrade dss-direct-deposit` dependency to reflect those changes but checking locally and with @gbalabasquer  we might need to remove the `lib/dss-interfaces` directory in `lib/dss-direct-deposit` manually as it seems it's not removed as part of the upgrade command:
> warning: unable to rmdir 'lib/dss-interfaces': Directory not empty

2022-03-28 19:14 UTC, julienmartinlevrai commented on src/DssExecLib.sol
> +        RwaOracleLike(getChangelogAddress("MIP21_LIQUIDATION_ORACLE")).bump(_ilk, _price * WAD);
done

2022-03-28 19:15 UTC, julienmartinlevrai commented
> Following [makerdao/dss-direct-deposit#35](https://github.com/makerdao/dss-direct-deposit/pull/35), I think we can `dapp upgrade dss-direct-deposit` dependency to reflect those changes but checking locally and with @gbalabasquer we might need to remove the `lib/dss-interfaces` directory in `lib/dss-direct-deposit` manually as it seems it's not removed as part of the upgrade command:
> 
> > warning: unable to rmdir 'lib/dss-interfaces': Directory not empty

done

2022-03-28 19:23 UTC, talbaneth approved these changes
LGTM

2022-03-29 20:45 UTC, naszam commented on src/DssExecLib.sol
> +    function setRWADebtCeiling(bytes32 _ilk, uint256 _ceiling, uint256 _price) public {
nit: consider naming the action `setRWAIlkDebtCeiling` following existing naming patterns.

2022-03-29 21:51 UTC, julienmartinlevrai commented on src/DssExecLib.sol
> +    function setRWADebtCeiling(bytes32 _ilk, uint256 _ceiling, uint256 _price) public {
done

2022-03-30 17:21 UTC, brianmcmichael commented on src/DssExecLib.sol
> +        RwaOracleLike(getChangelogAddress("MIP21_LIQUIDATION_ORACLE")).bump(_ilk, _price * WAD);
I think it's probably ok to use the existing function here as it will inherit any guard rails we add later, though I'm not sure what guard rails we'd add to that function...

2022-03-30 17:26 UTC, naszam commented on src/DssExecLib.sol
> +        setValue(vat(), _ilk, "line", _ceiling * RAD);
checking `bump` more closely, I think it assumes an increase in price `val` and so in the ilk debt ceiling, based on the formula in the spell, as the price should be originally set during the onboarding via the `init` function and the debt ceiling set following current collateral onboarding patterns.
I'm wondering if the action should also include the global debt ceiling increase (via `_global` flag) and maybe renamed into `increaseRWAIlkDebtCeiling` as well for clarity, following existing pattern (e.g. `increaseIlkDebtCeiling`).
cc: @godsflaw @brianmcmichael

2022-03-30 17:59 UTC, julienmartinlevrai commented on src/DssExecLib.sol
> +        setValue(vat(), _ilk, "line", _ceiling * RAD);
You are right that in practice, the debt ceiling of MIP21 collateral will only increase. However, the semantics of the `increaseIlkDebtCeiling()` function would require the `_ceiling` parameter to be a delta instead of an absolute amount. This is problematic for the `_price` parameter, because if it is left as an absolut amount it breaks the semantics and can be confusing, and if it is required to be a delta it becomes harder to calculate.

2022-03-30 18:17 UTC, brianmcmichael commented on src/DssExecLib.sol
> +        setValue(vat(), _ilk, "line", _ceiling * RAD);
We can decrease the ilk debt ceiling, we just can't decrease the price.

`set` is therefore probably fine here, but maybe we want a require or at least a dev comment that `_price` is greater than or equal to the pip price.

The `setIlkDebtCeiling()` function doesn't currently have a global bool because it wasn't clear if the added overhead to determine whether an increase or decrease was happening was worth the expense.

2022-03-30 18:18 UTC, brianmcmichael commented on src/DssExecLib.sol
> +        setValue(vat(), _ilk, "line", _ceiling * RAD);
```suggestion
        setIlkDebtCeiling(_ilk, _ceiling);
```

2022-03-30 18:52 UTC, julienmartinlevrai commented on src/DssExecLib.sol
> +        setValue(vat(), _ilk, "line", _ceiling * RAD);
I will add that as a comment as the require already is in place, except deeper in the call stack

2022-03-30 20:13 UTC, julienmartinlevrai commented on src/DssExecLib.sol
> +        setValue(vat(), _ilk, "line", _ceiling * RAD);
done

2022-03-30 20:54 UTC, naszam commented on src/DssExecLib.sol
> +        require(_ceiling < WAD);
I think this check can be removed as already present in [setIlkDebtCeiling](https://github.com/makerdao/dss-exec-lib/blob/master/src/DssExecLib.sol#L612)

2022-03-30 20:55 UTC, naszam commented on src/DssExecLib.sol
> +        @param _ceiling  The new debt ceiling in natural units (e.g. set 10m DAI as 10_000_000)
I think we should keep the naming convention `_amount` to avoid confusion

2022-03-30 20:57 UTC, julienmartinlevrai commented on src/DssExecLib.sol
> +        @param _ceiling  The new debt ceiling in natural units (e.g. set 10m DAI as 10_000_000)
Since the price is also an amount, I think it is actually less confusing to be more specific

2022-03-30 21:01 UTC, julienmartinlevrai commented on src/DssExecLib.sol
> +        require(_ceiling < WAD);
done

2022-03-30 21:05 UTC, naszam commented on src/DssExecLib.sol
> +        @param _ceiling  The new debt ceiling in natural units (e.g. set 10m DAI as 10_000_000)
I don't have a strong objection, but I think it would keep it consistent with the underlying `setIlkDebtCeiling` input parameter naming convention.

2022-03-30 21:10 UTC, naszam commented on src/DssExecLib.sol
> +        @dev note: _price should be higher than the current oracle price
```suggestion
        @dev note: _price should be greater than or equal to the current oracle price
```

2022-03-31 17:44 UTC, naszam commented on src/DssAction.sol
> +    function officeHours() public virtual view returns (bool) {
nit: I would put the `view` before the `virtual`

2022-03-31 17:53 UTC, naszam commented on src/DssExec.sol
> +// Copyright (C) 2021-2022 Dai Foundation
wondering if the license changes are correct (dates and keep the old one together with the new one) in the source files, following the recent discussion on `dss` repo, or it should be only Dai Foundation?
cc: @gbalabasquer

2022-03-31 17:54 UTC, naszam commented on src/test/DssTestAction.sol
> +    function officeHours() public override view returns (bool) {
nit: same as above, I would put the `view` after `public`

2022-03-31 18:06 UTC, naszam commented
Checked (deps):
- MIP21-RWA-Example (installed)
    - `69bb350` (latest on master)
- dss (upgraded, changes introduced in `join.sol` (events)
    - `c666ab1` (not latest on master)
- dss-direct-deposit (upgraded)
    - `f1e01ad` (latest on master)
- dss-interfaces (upgraded)
    - `a82bc3a` (not latest on master)
- ilk-registry (upgraded)
    - `81ba973` (latest on master)
  
I'm not sure if more dependencies upgrades are required at this stage and regarding the `dss` upgrade, I'm wondering if it's required and if it should be kept in sync here if there are no remapping issues (It seems that last upgrade was pointing at `d688ebb` due to `dss-test`, `dss-token` and `ds-value` upgrades).
  cc: @brianmcmichael

2022-03-31 18:19 UTC, naszam commented on src/DssExecLib.sol
> +    function setRWAIlkDebtCeiling(bytes32 _ilk, uint256 _ceiling, uint256 _price) public {
Consider adding documentation for the action in the readme regarding the behaviour and usage.

2022-03-31 19:35 UTC, julienmartinlevrai commented on src/DssAction.sol
> +    function officeHours() public virtual view returns (bool) {
done

2022-03-31 19:35 UTC, julienmartinlevrai commented on src/DssExec.sol
> +// Copyright (C) 2021-2022 Dai Foundation
done

2022-03-31 19:37 UTC, julienmartinlevrai commented
> I'm not sure if more dependencies upgrades are required at this stage and regarding the `dss` upgrade, I'm wondering if it's required and if it should be kept in sync here if there are no remapping issues (It seems that last upgrade was pointing at `d688ebb` due to `dss-test`, `dss-token` and `ds-value` upgrades). cc: @brianmcmichael

I think it is a good idea to upgrade. I don’t know in what dependency hell I am getting myself into, but yes.

2022-03-31 20:19 UTC, julienmartinlevrai commented
> > I'm not sure if more dependencies upgrades are required at this stage and regarding the `dss` upgrade, I'm wondering if it's required and if it should be kept in sync here if there are no remapping issues (It seems that last upgrade was pointing at `d688ebb` due to `dss-test`, `dss-token` and `ds-value` upgrades). cc: @brianmcmichael
> 
> I think it is a good idea to upgrade. I don’t know in what dependency hell I am getting myself into, but yes.

After talking with @naszam, I agree that this dependencies upgrade deserves its own set of PRs.

2022-03-31 20:48 UTC, naszam commented on src/DssExecLib.sol
> +    function setRWAIlkDebtCeiling(bytes32 _ilk, uint256 _ceiling, uint256 _price) public {
wondering if it would be better to include the action into a separate action sub section.

2022-04-04 12:38 UTC, naszam commented on src/test/DssAction.t.sol
> +        DSToken token = new DSToken(string(abi.encodePacked(ilk)));
wondering why the `RwaToken` is not used instead.

2022-04-04 12:41 UTC, naszam commented on src/test/DssAction.t.sol
> +        uint256 val = line / RAY; // TODO calculation
It seems the `val` (`price`) calculation is missing

2022-04-05 14:07 UTC, naszam commented on src/test/DssAction.t.sol
> +        assertEq(price, 55 * MILLION * WAD);
I would include a test to validate the `val` formula in the `init_rwa` against the [computation](https://github.com/makerdao/spells-mainnet/blob/master/archive/2021-07-17-DssSpell/DssSpell.sol#L55) showed in the spell, using the [assertEqApprox](https://github.com/makerdao/spells-mainnet/blob/master/src/DssSpell.t.base.sol#L145) test assertion.

```suggestion
        (,address pip,,) = rwaOracle.ilks("6s");
        uint256 price = uint256(PipLike(pip).read());
        assertEqApprox(price, 22_278_900 * WAD, WAD); // 20MM * 1.03^2 * 1.05
        action.setRWAIlkDebtCeiling_test("6s", 50 * MILLION, 55 * MILLION);
        (,,, uint256 line,) = vat.ilks("6s");
        assertEq(line, 50 * MILLION * RAD);
        price = uint256(PipLike(pip).read());
        assertEq(price, 55 * MILLION * WAD);
```

2022-04-05 16:30 UTC, naszam commented on src/test/DssAction.t.sol
> +        assertEqApprox(price, 22_278_900 * WAD, WAD); // 20MM * 1.03^2 * 1.05
`assertEqApprox` is required as not provided by `ds-test`

2022-04-05 16:33 UTC, julienmartinlevrai commented on src/test/DssAction.t.sol
> +        assertEq(price, 55 * MILLION * WAD);
done

2022-04-05 16:33 UTC, julienmartinlevrai commented on src/test/DssAction.t.sol
> +        assertEqApprox(price, 22_278_900 * WAD, WAD); // 20MM * 1.03^2 * 1.05
added

2022-04-05 18:28 UTC, naszam commented on src/test/DssAction.t.sol
> +
I would include a fail test for the edge case where `_price` < `pip.read` (current oracle price), following previous discussion.

```solidity
    function testFail_setRWAIlkDebtCeiling() public {
        action.setRWAIlkDebtCeiling_test("6s", 50 * MILLION, 20 * MILLION); // Fail
    }
```

2022-04-05 18:42 UTC, naszam commented on src/test/DssAction.t.sol
> +        assertEq(price, 55 * MILLION * WAD);
Consider extend the test to also include ceiling decrease, where the `_price` is equal to `pip.read` (current oracle price) following previous discussion.

```suggestion
        action.setRWAIlkDebtCeiling_test("6s", 50 * MILLION, 55 * MILLION); // Increase
        (,,, uint256 line,) = vat.ilks("6s");
        assertEq(line, 50 * MILLION * RAD);
        price = uint256(PipLike(pip).read());
        assertEq(price, 55 * MILLION * WAD);
        action.setRWAIlkDebtCeiling_test("6s", 40 * MILLION, 55 * MILLION); // Decrease
        (,,, line,) = vat.ilks("6s");
        assertEq(line, 40 * MILLION * RAD);
        price = uint256(PipLike(pip).read());
        assertEq(price, 55 * MILLION * WAD);
```

2022-04-05 20:29 UTC, naszam reviewed
Checked:

- License Changes
- DssExecLib `setRWAIlkDebtCeiling` Action
- Action Test Coverage
- README Changes
- Test PASS

Notes: left some suggestions to improve test coverage

LGTM

2022-04-05 21:07 UTC, julienmartinlevrai commented on src/test/DssAction.t.sol
> +
done

2022-04-05 21:59 UTC, naszam approved these changes
LGTM

2022-04-13 11:07 UTC, talbaneth commented on src/DssAction.sol
> +    bool OFFICE_HOURS = true;
We shouldn't use storage variables in the spell action.
Specifically this field will collide with the `owner` field of the pause proxy 
during spell execution (so you should get wrong office hours value as it reads the delegating contract stoarge slot):

`https://github.com/dapphub/ds-pause/blob/master/src/pause.sol#L110`

2022-04-13 11:28 UTC, talbaneth commented on src/DssExecLib.sol
> +        @dev note: _price should be greater than or equal to the current oracle price
Technically it's `_price * WAD` that should be greater or equal to the current oracle price.
We might want to change the comment.

2022-04-13 16:21 UTC, julienmartinlevrai commented on src/DssAction.sol
> +    bool OFFICE_HOURS = true;
This is a very good point, @talbaneth, thank you so much for spotting that !
This takes us back to the discussion with @brianmcmichael about the state mutability modifier of the `officeHours` function. Since that function will be executed in the context of the Pause Proxy, it does not make sense for it to be a `view` because the only storage slot it could read is `owner`. So I will change it to `pure`.

2022-04-13 16:27 UTC, julienmartinlevrai commented on src/DssAction.sol
> +    bool OFFICE_HOURS = true;
done

2022-04-13 16:27 UTC, julienmartinlevrai commented on src/DssExecLib.sol
> +        @dev note: _price should be greater than or equal to the current oracle price
done

2022-04-13 16:56 UTC, talbaneth commented on src/DssAction.sol
> +    bool OFFICE_HOURS = true;
mm we might still want to do external calls to non pure functions from other contracts.
I think it's ok to leave it as before for now and ignore the warning.

2022-04-13 17:22 UTC, julienmartinlevrai commented on src/DssAction.sol
> +    bool OFFICE_HOURS = true;
done

2022-04-14 10:45 UTC, talbaneth commented on src/DssExecLib.sol
> +        @dev note: _price * WAD should be greater than or equal to the current oracle price
```suggestion
        @dev note: _price * WAD should be greater than or equal to the current oracle price
```
I'm seeing that line with an `NBSP` special character:
![image](https://user-images.githubusercontent.com/27555714/163373520-b53d679d-1efd-4d46-9d9d-f85b0be5e254.png)

I suspect this is maybe because you did the space when you were on french mode? (just guessing based on this - https://intellij-support.jetbrains.com/hc/en-us/community/posts/360009442799-2020-2-showing-NBSP-).

Let's see if this suggestion solves that.

2022-04-14 11:04 UTC, talbaneth approved these changes
Apart from the comment on the `NBSP` thing this looks good to me.

Would love to hear others opinion about this but in general I think it's better to do unrelated changes (adding `view` modifiers, license stuff) in separate PR/s.
Otherwise it drives focus away from the actual change and makes the reviewing harder.

2022-04-14 15:02 UTC, julienmartinlevrai commented
Hello @talbaneth I think you are right about not adding unrelated changes. Sorry for that, I will keep it in mind for future PRs.

2022-04-14 15:11 UTC, talbaneth commented
btw the `NPBS` thing is gone now, which is good.

2022-05-04 17:16 UTC, brianmcmichael commented on src/DssExecLib.sol
> +        RwaOracleLike(getChangelogAddress("MIP21_LIQUIDATION_ORACLE")).bump(_ilk, _price * WAD);
Interesting point to note here that `bump` is a `WAD` in this liquidation oracle and a `RAD` in the vow. Nothing actionable but pointing it out. Might be worth adding a comment to the MIP21 repo as the precision is not indicated there.

2022-05-04 17:21 UTC, brianmcmichael approved these changes
Looks good. Only minor comments.

2022-05-06 23:16 UTC, brianmcmichael commented on src/test/DssAction.t.sol
> +    function assertEqApprox(uint256 _a, uint256 _b, uint256 _tolerance) internal {
This could probably use some documentation. It looks like _tolerance is a straight delta but we might want to mention what format this takes. (i.e. not a percentage)

2022-05-06 23:21 UTC, brianmcmichael requested changes
A couple of minor things around documentation.

2022-05-09 17:46 UTC, julienmartinlevrai commented on src/test/DssAction.t.sol
> +    string constant doc = "QmdmAUTU3sd9VkdfTZNQM6krc9jsKgF2pz7W1qvvfJo1xk";
done

2022-05-09 18:20 UTC, julienmartinlevrai commented on src/test/DssAction.t.sol
> +    function assertEqApprox(uint256 _a, uint256 _b, uint256 _tolerance) internal {
done

2022-05-10 19:04 UTC, merged