Remove dependencies
makerdao/dss-exec-lib pull request #97
Opened 2022-11-30 18:35 UTC by gbalabasquer

2022-11-30 18:50 UTC, gbalabasquer commented
Once this gets merged I'll move on with a new PR for upgrading to solc 0.8.x.

2022-11-30 19:02 UTC, iamchrissmith requested changes
one clean up item and two questions

:mechanical_arm:

2022-11-30 19:02 UTC, iamchrissmith commented on Makefile
> +build        :; DAPP_BUILD_OPTIMIZE=1 DAPP_BUILD_OPTIMIZE_RUNS=200 dapp --use solc:0.6.12 build
if we are moving from dapp to forge, do we want to switch these too:
```
forge build
forge clean
forge create
```
etc?

2022-11-30 21:49 UTC, gbalabasquer commented on src/test/DssAction.t.sol
> +    // }
Done!

2022-11-30 21:56 UTC, gbalabasquer commented on src/test/DssAction.t.sol
> +contract MockUniPair {
Done!

2022-11-30 21:57 UTC, gbalabasquer commented on Makefile
> +build        :; DAPP_BUILD_OPTIMIZE=1 DAPP_BUILD_OPTIMIZE_RUNS=200 dapp --use solc:0.6.12 build
the thing is `forge create` apparently doesn't work the same than `dapp create` (we are still using the last one I believe). And we need to `build` using `dapp` in order to be able to create with it.
I'd guess `dapp clean` could be replaced without any problem.

2022-11-30 21:59 UTC, gbalabasquer commented on Makefile
> +build        :; DAPP_BUILD_OPTIMIZE=1 DAPP_BUILD_OPTIMIZE_RUNS=200 dapp --use solc:0.6.12 build
Yeah actually, `forge clean` also removed `cache` directory which should be fine. For now I'm changing only that one.

2022-11-30 21:59 UTC, gbalabasquer commented on Makefile
> +build        :; DAPP_BUILD_OPTIMIZE=1 DAPP_BUILD_OPTIMIZE_RUNS=200 dapp --use solc:0.6.12 build
Done!

2022-12-01 16:53 UTC, iamchrissmith approved these changes
lgtm!

2022-12-04 20:16 UTC, rockyfour approved these changes
Changes LGTM.
Tests pass.

2022-12-04 21:08 UTC, naszam commented on src/test/Mocks.sol
> +// SPDX-License-Identifier: AGPL-3.0-or-later
```suggestion
// SPDX-FileCopyrightText: © 2022 Dai Foundation <www.daifoundation.org>
// SPDX-License-Identifier: AGPL-3.0-or-later
```

2022-12-04 21:08 UTC, naszam commented on src/test/Mocks.sol
> +// Copyright (C) 2022 Dai Foundation
```suggestion
```

2022-12-05 11:36 UTC, merged